version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 120569623227.dkr.ecr.ap-south-1.amazonaws.com
            - echo Fetching REACT_APP_API_URL from SSM Parameter Store...
            - export REACT_APP_API_URL=$(aws ssm get-parameter --name "/nexevent/REACT_APP_API_URL" --with-decryption --region ap-south-1 --query Parameter.Value --output text)
    build:
        commands:
            - echo Building the React app Docker image...
            - docker build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL -t nexevent-frontend:latest ./client
            - echo Tagging the Docker image...
            - docker tag nexevent-frontend:latest 120569623227.dkr.ecr.ap-south-1.amazonaws.com/nexevent/frontend:latest
    post_build:
        commands:
            - echo Pushing the Docker image to ECR...
            - docker push 120569623227.dkr.ecr.ap-south-1.amazonaws.com/nexevent/frontend:latest
            - echo Creating imagedefinitions.json file...
            - printf '[{"name":"react-frontend","imageUri":"120569623227.dkr.ecr.ap-south-1.amazonaws.com/nexevent/frontend:latest"}]' > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
