version: "3.8"

services:
    backend:
        build:
            context: ./server
        container_name: django-backend
        command: >
            sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
        volumes:
            - ./server:/app
        ports:
            - "8000:8000"

    frontend:
        build:
            context: ./client
        container_name: react-frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
