version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: django-backend
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
      - ./server/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
