# Generated by Django 5.1 on 2024-09-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="feature_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
