# Generated by Django 5.1 on 2024-09-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_feature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("games", "Games"),
                    ("sports", "Sports"),
                    ("arts", "Arts"),
                    ("film", "Film"),
                    ("literature", "Literature"),
                    ("technology", "Technology"),
                    ("culture", "Culture"),
                    ("lifestyle", "Lifestyle"),
                    ("charity", "Charity"),
                    ("fashion", "Fashion"),
                    ("kids", "Kids"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
