# Generated by Django 5.1 on 2024-08-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_appuser_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="user_id",
            new_name="id",
        ),
    ]
