# Generated by Django 5.1.1 on 2024-09-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_appuser_date_joined_appuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ATTENDEE", "Attendee"),
                    ("MANAGER", "Manager"),
                    ("ADMIN", "Admin"),
                ],
                default="ATTENDEE",
                max_length=10,
            ),
        ),
    ]
