version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 120569623227.dkr.ecr.ap-south-1.amazonaws.com
            - echo "Checking AWS Credentials"
            - aws sts get-caller-identity
    build:
        commands:
            - echo Building the Django app Docker image...
            - docker build -t nexevent-backend:latest ./server
            - echo Tagging the Docker image...
            - docker tag nexevent-backend:latest 120569623227.dkr.ecr.ap-south-1.amazonaws.com/nexevent/backend:latest
    post_build:
        commands:
            - echo Pushing the Docker image to ECR...
            - docker push 120569623227.dkr.ecr.ap-south-1.amazonaws.com/nexevent/backend:latest
            - echo Creating imagedefinitions.json file...
            - printf '[{"name":"django-backend","imageUri":"120569623227.dkr.ecr.ap-south-1.amazonaws.com/nexevent/backend:latest"}]' > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
