# Generated by Django 5.1.1 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rsvp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="rsvp_status",
            field=models.CharField(
                choices=[
                    ("ATTENDING", "Attending"),
                    ("NOT_ATTENDING", "Not Attending"),
                    ("MAYBE", "Maybe"),
                ],
                default="ATTENDING",
                max_length=15,
            ),
        ),
    ]
